name: build_and_push_image
on: push
jobs:
  build_and_push_image:
    name: build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v17.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: contains(steps.changed-files.outputs.modified_files, 'Dockerfile')

      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/debian_arm_v7_ros
          push: true
          platforms: linux/arm/v7
        if: contains(steps.changed-files.outputs.modified_files, 'Dockerfile')
